export enum Actions {
  RENAME = "RENAME",
  DOWNLOAD = "DOWNLOAD",
  PREVIEW = "PREVIEW",
  // SHARE = "SHARE",
  // GET_LINK = "GET_LINK",
  REMOVE = "REMOVE",
  ASSIGN_TYPE = "ASSIGN_TYPE",
  EDIT_METADATA = "EDIT_METADATA",
  // SET_NODE_COVER = "SET_NODE_COVER",
}
